name: publish

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build-images:
    uses: ./.github/workflows/build-and-publish-images.yml
    with:
      push: true
    secrets: inherit
